version: 1.0.{build}
platform:
  - x64

install:
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user # Create the conan data directory
  - conan --version

build_script:
  - mkdir build
  - conan install . -o gtest:shared=True
  - cd build
  - cmake ../ -DBUILD_TEST=TRUE  -G "Visual Studio 14 2015 Win64"
  - cmake --build . --config Release

test_script:
  - cd bin
  - encryption_test.exe
